# Generated by Django 5.2.2 on 2025-07-12 10:15

import django.db.models.deletion
import ocrtesting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherDocument',
            fields=[
                ('fiscal_year', models.IntegerField(default=2025)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('doc_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('recipients', models.ManyToManyField(blank=True, to='ocrtesting.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('fiscal_year', models.IntegerField(default=2025)),
                ('document_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20)),
                ('for_field', models.CharField(blank=True, max_length=200, null=True)),
                ('from_field', models.CharField(blank=True, max_length=200, null=True)),
                ('thru', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('recipients', models.ManyToManyField(blank=True, to='ocrtesting.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLetter',
            fields=[
                ('fiscal_year', models.IntegerField(default=2025)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('from_field', models.CharField(max_length=200)),
                ('to_or_thru', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('recipients', models.ManyToManyField(blank=True, to='ocrtesting.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='MOAU',
            fields=[
                ('fiscal_year', models.IntegerField(default=2025)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('first_party_agency', models.CharField(blank=True, max_length=200, null=True)),
                ('first_party_representative', models.CharField(blank=True, max_length=200, null=True)),
                ('second_party_agency', models.CharField(blank=True, max_length=200, null=True)),
                ('second_party_representative', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('recipients', models.ManyToManyField(blank=True, to='ocrtesting.recipient')),
                ('signatories', models.ManyToManyField(blank=True, to='ocrtesting.signatory')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOrder',
            fields=[
                ('fiscal_year', models.IntegerField(default=2025)),
                ('document_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('recipients', models.ManyToManyField(blank=True, to='ocrtesting.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='TravelOrder',
            fields=[
                ('fiscal_year', models.IntegerField(default=2025)),
                ('document_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('recipients', models.ManyToManyField(blank=True, to='ocrtesting.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ocrtesting.models.document_file_upload_to)),
                ('content_type', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('communication_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocrtesting.communicationletter')),
                ('memorandum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocrtesting.memorandum')),
                ('moau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocrtesting.moau')),
                ('other_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocrtesting.otherdocument')),
                ('special_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocrtesting.specialorder')),
                ('travel_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocrtesting.travelorder')),
            ],
        ),
    ]
