# Generated by Django 5.2.2 on 2025-07-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrtesting', '0002_alter_travelorder_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationletter',
            name='category',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20),
        ),
    ]
