# Generated by Django 5.2.2 on 2025-07-21 13:48

import ocrtesting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrtesting', '0004_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationletter',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='gdrive_file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memorandum',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moau',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherdocument',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ocrtesting.models.document_file_upload_to),
        ),
    ]
