# Generated by Django 5.2.2 on 2025-08-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrtesting', '0005_communicationletter_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationletter',
            name='received_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='communicationletter',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memorandum',
            name='received_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memorandum',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moau',
            name='received_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='moau',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherdocument',
            name='received_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='received_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='received_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
