# Generated by Django 5.2.14 on 2026-05-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrtesting', '0006_communicationletter_received_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationletter',
            name='fiscal_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='fiscal_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='moau',
            name='fiscal_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='otherdocument',
            name='fiscal_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='fiscal_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='fiscal_year',
            field=models.IntegerField(default=2026),
        ),
    ]
