# Generated by Django 5.2.14 on 2026-05-19 05:54

from django.db import migrations, models


def _timestamp_string(dt):
    # dt might be None for older data
    if not dt:
        from django.utils import timezone

        dt = timezone.now()
    return dt.strftime('%Y%m%d%H%M%S%f')


def _get_doc_year(obj):
    from django.utils import timezone

    if getattr(obj, 'date', None):
        return int(obj.date.year)
    if getattr(obj, 'fiscal_year', None):
        try:
            return int(obj.fiscal_year)
        except (TypeError, ValueError):
            pass
    return int(timezone.now().year)


def _generate_unique_id(model, prefix: str, saved_at, doc_year: int, used_ids: set[str]):
    base = f"{prefix}_{_timestamp_string(saved_at)}_{int(doc_year)}"
    candidate = base
    suffix = 1
    while candidate in used_ids or model.objects.filter(document_id=candidate).exists():
        candidate = f"{base}_{suffix}"
        suffix += 1
    used_ids.add(candidate)
    return candidate


def backfill_document_ids(apps, schema_editor):
    CommunicationLetter = apps.get_model('ocrtesting', 'CommunicationLetter')
    MOAU = apps.get_model('ocrtesting', 'MOAU')
    OtherDocument = apps.get_model('ocrtesting', 'OtherDocument')

    # Backfill only rows that don't have a value yet.
    for model, prefix in (
        (CommunicationLetter, 'COMM'),
        (MOAU, 'MOAU'),
        (OtherDocument, 'OTHR'),
    ):
        used_ids: set[str] = set(
            model.objects.exclude(document_id__isnull=True).exclude(document_id='').values_list('document_id', flat=True)
        )

        qs = model.objects.filter(document_id__isnull=True) | model.objects.filter(document_id='')
        for obj in qs.iterator():
            obj.document_id = _generate_unique_id(
                model=model,
                prefix=prefix,
                saved_at=getattr(obj, 'upload_date', None),
                doc_year=_get_doc_year(obj),
                used_ids=used_ids,
            )
            obj.save(update_fields=['document_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('ocrtesting', '0007_alter_communicationletter_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationletter',
            name='document_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='moau',
            name='document_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='otherdocument',
            name='document_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='document_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='document_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='document_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.RunPython(backfill_document_ids, migrations.RunPython.noop),
    ]
