# Generated by Django 5.2.3 on 2025-06-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='researcher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='secretariat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='stakeholder',
            field=models.BooleanField(default=False),
        ),
    ]
